version: "1.0"
redisHost: "macmini.local"
redisPort: 6388
redisPass: welcome1

logging:
  level: INFO
  loggers:
    org.gpc4j.ncaaf.FootballConfiguration: DEBUG
    org.gpc4j.ncaaf.resources: DEBUG
    org.gpc4j.ncaaf.hystrix: DEBUG

  appenders:
    - type: console
      threshold: TRACE
      logFormat: "%d{dd MMM HH:mm:ss} %-5level %C{1} %M %msg%n"

#      logFormat: "%-5level [%date{ISO8601}] [%X{MDC_VAR}] [%thread]: %c:%method:%line- %msg%n"
#      logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%class{0}:%method:%line] [%thread] [-[%msg]-] %n'
#      logFormat: "%d{dd MMM HH:mm:ss} %-5level %class{0} %method %msg%n"
