version: "1.0"
redisHost: "macmini.local"
redisPort: 6388
redisPass: welcome1

server:
  applicationConnectors:
  - type: http 
    port: 9020
  adminConnectors:
  - type: http
    port: 9021

logging:
  level: INFO
  loggers:
    org.gpc4j.ncaaf.FootballConfiguration: INFO
    org.gpc4j.ncaaf.resources: INFO

  appenders:
    - type: file
      currentLogFilename: /var/log/ncaaf.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/log/ncaaf-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%d{dd MMM HH:mm:ss} %-5level %C{1} %M %msg%n"


