# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - '*'
      - '!master'   # excludes master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      APP_NAME: ncaaf

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Substitute Secrets
        run: |
          sed -e 's/KUBE_SERVER/${{ secrets.KUBE_SERVER }}/g' kube_config > config.1
          sed -e 's/KUBE_TOKEN/${{ secrets.KUBE_TOKEN }}/g' config.1 > k_config
          cat k_config
          # Set hostname and Docker image to App/Branch/Build..
          sed -e "s/HOSTNAME/${APP_NAME}\.${GITHUB_REF##*\/}/g" application-template.yaml > a1.yaml
          sed -e "s/BRANCH/${GITHUB_REF##*\/}/g" a1.yaml > a2.yaml
          sed -e "s/BUILD/${GITHUB_RUN_NUMBER}/g" a2.yaml > application.yaml

      - name: Display Config
        run: |
          cat k_config
          cat application.yaml

      # Step that does that actual cache save and restore
      - name: Cache LOcal Maven Repository
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-repo
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Maven Package
        run: mvn -B -DskipTests package

      - name: Docker Build
        env:
          BRANCH: ${GITHUB_REF##*/}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -t lh32469/${APP_NAME}-${GITHUB_REF##*/}:${GITHUB_RUN_NUMBER} .

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Push image to Docker Hub
        run: docker push lh32469/${APP_NAME}-${GITHUB_REF##*/}:${GITHUB_RUN_NUMBER}

      - name: Check existing Kubernetes Deployment
        id: deployment_check
        env:
          KUBECONFIG: ./k_config
        run: kubectl get -n ${APP_NAME}-${GITHUB_REF##*/} deployment/${APP_NAME}
        continue-on-error: true

      - name: Create new Kubernetes Deployment
        if: steps.deployment_check.outcome != 'success'
        env:
          KUBECONFIG: ./k_config
        run: |
          kubectl create namespace ${APP_NAME}-${GITHUB_REF##*/}
          kubectl apply -f application.yaml -n ${APP_NAME}-${GITHUB_REF##*/}

      - name: Deploy new image to Kubernetes
        env:
          KUBECONFIG: ./k_config
        run: >
          kubectl set image -n ${APP_NAME}-${GITHUB_REF##*/} deployment/${APP_NAME}
          ${APP_NAME}=lh32469/${APP_NAME}-${GITHUB_REF##*/}:${GITHUB_RUN_NUMBER}


  env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Environment Variables
        run: env
      - name: List Directory
        env:
          BRANCH: ${GITHUB_REF##*/}
        run: ls -l
      - name: Print Branch Name
        env:
          BRANCH: ${GITHUB_REF##*/}
        run: echo BRANCH=${BRANCH}
